name: Build manylinux wheels

on:
  workflow_dispatch:
    # No input required, possibly a version?

jobs:
  build_package_amd64:
    runs-on: ubuntu-latest
    env:
      PLAT: manylinux2014_x86_64
    container:
      image: quay.io/pypa/manylinux2014_x86_64
      options: --user=root # Will be installing packages
    steps:
    - name: Install clingo dependencies
      run: yum install re2c bison
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build wheels
      run: bash build.sh
