name: Build manylinux wheels

on:
  workflow_dispatch:
    # No input required, possibly a version?

jobs:
  build_packages:
    runs-on: ubuntu-latest
    env:
      PLAT: ${{ matrix.image }}
    strategy:
      matrix:
        image: [manylinux2014_x86_64, manylinux2014_ppc64le]
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64, ppc64le
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: docker://quay.io/pypa/${{ matrix.image }}
      with:
        args: >
          bash -c
          "yum install -y re2c bison &&
          bash build.sh"
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: wheelhouse/
        repository_url: https://test.pypi.org/legacy/
